// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: hello.proto
// </auto-generated>
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace Hello {
  /// <summary>
  ///定义服务类似接口,定义客户端和服务端需要调用/实现的方法
  /// </summary>
  public static partial class HelloSerivce
  {
    static readonly string __ServiceName = "hello.HelloSerivce";

    static readonly grpc::Marshaller<global::Hello.HelloRequest> __Marshaller_HelloRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Hello.HelloRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Hello.HelloReply> __Marshaller_HelloReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Hello.HelloReply.Parser.ParseFrom);

    static readonly grpc::Method<global::Hello.HelloRequest, global::Hello.HelloReply> __Method_tickInfo = new grpc::Method<global::Hello.HelloRequest, global::Hello.HelloReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "tickInfo",
        __Marshaller_HelloRequest,
        __Marshaller_HelloReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Hello.HelloReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of HelloSerivce</summary>
    public abstract partial class HelloSerivceBase
    {
      /// <summary>
      ///方法可以传递多个参数,和返回多个参数
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::Hello.HelloReply> tickInfo(global::Hello.HelloRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for HelloSerivce</summary>
    public partial class HelloSerivceClient : grpc::ClientBase<HelloSerivceClient>
    {
      /// <summary>Creates a new client for HelloSerivce</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public HelloSerivceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for HelloSerivce that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public HelloSerivceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected HelloSerivceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected HelloSerivceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      ///方法可以传递多个参数,和返回多个参数
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Hello.HelloReply tickInfo(global::Hello.HelloRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return tickInfo(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///方法可以传递多个参数,和返回多个参数
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Hello.HelloReply tickInfo(global::Hello.HelloRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_tickInfo, null, options, request);
      }
      /// <summary>
      ///方法可以传递多个参数,和返回多个参数
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Hello.HelloReply> tickInfoAsync(global::Hello.HelloRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return tickInfoAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///方法可以传递多个参数,和返回多个参数
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Hello.HelloReply> tickInfoAsync(global::Hello.HelloRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_tickInfo, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override HelloSerivceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new HelloSerivceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(HelloSerivceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_tickInfo, serviceImpl.tickInfo).Build();
    }

  }
}
#endregion
